In [1]:
import numpy as np 
import pandas as pd

In [191]:
manga = pd.read_csv('data.csv')

In [160]:
manga.to_csv('cleaneddata.csv')

In [213]:
manga.head()

,title,description,rating,year,tags,cover,new
0,Salad Days (Tang LiuZang) - Part 2,The second season of Salad Days Tang LiuZang .,4.7,2021.0,BL Manhua Romance Shounen ai Sports Webto...,https://cdn.anime-planet.com/manga/primary/sal...,4.7
1,The Master of Diabolism,As the grandmaster who founded the Demonic Sec...,4.7,2017.0,Action Adventure BL Comedy Manhua Mystery...,https://cdn.anime-planet.com/manga/primary/the...,4.7
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,Set in 1890 Steel Ball Run spotlights Gyro Ze...,4.7,2004.0,Action Adventure Horror Mystery Seinen 19...,https://cdn.anime-planet.com/manga/primary/joj...,4.7
3,A Sign of Affection,Yuki is a typical college student whose world...,4.7,2019.0,Romance Shoujo Slice of Life Disability,https://cdn.anime-planet.com/manga/primary/a-s...,4.7
4,Moriarty the Patriot,Before he was Sherlock’s rival Moriarty fough...,4.7,2016.0,Mystery Shounen Detectives England Europe ...,https://cdn.anime-planet.com/manga/primary/mor...,4.7

In [158]:
manga = manga.drop(manga.columns[3], axis = 1)

In [142]:
manga['year'][1]

'0        0        0        2021.0\\n1        2017.0\\n2  ...\n1        0        0        2021.0\\n1        2017.0\\n2  ...\n2        0        0        2021.0\\n1        2017.0\\n2  ...\n3        0        0        2021.0\\n1        2017.0\\n2  ...\n4        0        0        2021.0\\n1        2017.0\\n2  ...\n                               ...                        \n70943    0        0        2021.0\\n1        2017.0\\n2  ...\n70944    0        0        2021.0\\n1        2017.0\\n2  ...\n70945    0        0        2021.0\\n1        2017.0\\n2  ...\n70946    0        0        2021.0\\n1        2017.0\\n2  ...\n70947    0        0        2021.0\\n1        2017.0\\n2  ...\nName: year, Length: 70093, dtype: object'

In [180]:
manga['tags'] = manga['tags'] + manga['new']

In [202]:
manga.isnull().sum()

title              0
description       31
rating         41077
year             824
tags               0
cover              0
dtype: int64

In [141]:
manga['year'] = str(manga['year'])

In [133]:

    for i in range(manga.shape[0]):

        manga['year'][i] = str(manga['year'][i])

C:\Users\User\AppData\Local\Temp\ipykernel_16156\3562125382.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  manga['year'][i] = str(manga['year'][i])
C:\Users\User\AppData\Local\Temp\ipykernel_16156\3562125382.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2021.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  manga['year'][i] = str(manga['year'][i])

KeyError: 2527

In [85]:
type(manga.iloc[0]['tags'])

str

In [190]:
manga.iloc[5]['tags']

'Comedy  Drama  Ecchi  Harem  Light Novels  Romance  Boarding School  School Life  Adapted to AnimeAt the prestigious Tokyo Metropolitan Advanced Nurturing High School, which aims to produce the country’s future leaders, students are given remarkable freedom. However, they also have to deal with a point system that decides one’s place in the school’s hierarchy! Ayanokoji Kiyotaka has landed at the bottom in the scorned Class D, where he meets Horikita Suzune, who’s determined to work her way back up to Class A, and Kushida Kikyo, who seems like she only wants to make friends. Can they advance through this school where cutthroat competition is the name of the game?Classroom of the Elite (Light Novel)'

In [91]:
manga['tags'].shape

(70948,)

In [108]:
manga['new']=manga['new'].map(lambda x: x.replace(':', ' ').replace("-", " "))

In [200]:
manga['description'][1]

'As the grandmaster who founded the Demonic Sect, Wei WuXian roamed the world in his wanton ways, hated by millions for the chaos he created. In the end, he was back-stabbed by his dearest shidi and killed by powerful clans that combined to overpower him. He incarnates into the body of a lunatic who was abandoned by his clan and is later, unwillingly, taken away by a famous cultivator among the clans—Lan WangJi, his archenemy.'

In [212]:
manga['description']=manga['description'].map(lambda x: x.replace(",", " ").replace('-', " ").replace("(", " ").replace(')', " "))

In [207]:
manga['new'] = manga['rating']

In [99]:

for i in range (manga['tags'].shape[0]):
    manga[i]['tags'] = manga[i]['tags'].replace("[", ' ').replace(']', '').replace("'", "").replace(",", " ")

KeyError: 0

In [12]:
manga.shape

(70948, 6)

In [80]:
manga['description'][0]

'The second season of\xa0Salad Days (Tang LiuZang).'

In [211]:
manga.isnull().sum()

title          0
description    0
rating         0
year           0
tags           0
cover          0
new            0
dtype: int64

In [124]:
null_data = manga[manga['description'].isnull()]

In [205]:
manga = manga.dropna(subset=['year'])

In [ ]:
manga.isnull()

In [67]:
str(manga.iloc[29871]['rating'])

'nan'

In [127]:
null_data.head()

,title,description,rating,year,tags,cover,new
14982,The Mountain Bird Cries at Dawn,NaN,3.8,2018.0,BL Yaoi,https://cdn.anime-planet.com/manga/primary/the...,The Mountain Bird Cries at Dawn
15830,Monster Hunter Epic,NaN,3.8,2011.0,Action Adventure Fantasy,https://cdn.anime-planet.com/manga/primary/mon...,Monster Hunter Epic
19279,Otome no Honki!!,NaN,3.6,2012.0,One Shot Romance Shoujo School Life,https://cdn.anime-planet.com/manga/primary/oto...,Otome no Honki!!
20673,My Monster Lover,NaN,3.6,2019.0,Josei Romance Smut,https://cdn.anime-planet.com/manga/primary/my-...,My Monster Lover
20858,Chitose Get You!!,NaN,3.5,2002.0,4-koma Comedy Seinen School Life Slapstick...,https://cdn.anime-planet.com/manga/primary/chi...,Chitose Get You!!

str

In [171]:
type(int(manga['new'][1]))

int

In [210]:
manga.fillna({'rating':0}, inplace=True)

In [187]:
i=0
for tag in manga['new']:
    if (tag<3.0):
        manga['new'][i] ='lowestranking'
    elif (tag>=3.0 and tag<3.5):
        manga['new'][i] ='lowranking'
    elif (tag>=3.5 and tag<4.0):
        manga['new'][i] ='midranking'
    elif (tag>=4.0 and tag<4.5):
        manga['new'][i] ='highranking'
    elif (tag>=4.5):
        manga['new'][i] ='highestranking'
    elif(tag==0):
        manga['new'][i] ='notrated'    
    
    i+=1

C:\Users\User\AppData\Local\Temp\ipykernel_16156\1059975269.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  manga['new'][i] ='highestranking'
C:\Users\User\AppData\Local\Temp\ipykernel_16156\1059975269.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  manga['new'][i] ='highestranking'
C:\Users\User\AppData\Local\Temp\ipykernel_16156\1059975269.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'highestranking' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  manga['new'][i] ='highestranking'