In [1]:
import numpy as np 
import pandas as pd

In [2]:
manga = pd.read_csv('cleaneddata3.csv')

In [9]:
new_df.to_csv('cleaneddata3.csv', index= False)

In [3]:
manga.head()

,title,tags,cover,rating
0,Salad Days (Tang LiuZang) - Part 2,BL Manhua Romance Shounen ai Sports Webto...,https://cdn.anime-planet.com/manga/primary/sal...,4.7
1,The Master of Diabolism,Action Adventure BL Comedy Manhua Mystery...,https://cdn.anime-planet.com/manga/primary/the...,4.7
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,Action Adventure Horror Mystery Seinen 19...,https://cdn.anime-planet.com/manga/primary/joj...,4.7
3,A Sign of Affection,Romance Shoujo Slice of Life Disability Yuk...,https://cdn.anime-planet.com/manga/primary/a-s...,4.7
4,Moriarty the Patriot,Mystery Shounen Detectives England Europe ...,https://cdn.anime-planet.com/manga/primary/mor...,4.7

In [7]:
manga.loc[5]['cover']

'https://cdn.anime-planet.com/manga/primary/classroom-of-the-elite-light-novel-1-285x403.jpg?t=1630446924'

In [4]:
manga.iloc[10]['cover']

'https://cdn.anime-planet.com/manga/primary/tower-of-god-part-3-1-190x266.jpg?t=1625921019'

In [4]:
manga.shape

(28000, 4)

In [17]:
manga.iloc[27997]

title                            The Conditions of Paradise
tags      Comedy  GL  Shoujo ai  Slice of Life  Adult Co...
cover     https://cdn.anime-planet.com/manga/primary/the...
rating                                                  3.2
Name: 27997, dtype: object

In [6]:
new_df = manga.head(28000)

In [10]:
new_df.to_csv('cleaneddata3.csv', index=False)

In [8]:
new_df.head()

,title,tags,cover,rating
0,Salad Days (Tang LiuZang) - Part 2,BL Manhua Romance Shounen ai Sports Webto...,https://cdn.anime-planet.com/manga/primary/sal...,4.7
1,The Master of Diabolism,Action Adventure BL Comedy Manhua Mystery...,https://cdn.anime-planet.com/manga/primary/the...,4.7
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,Action Adventure Horror Mystery Seinen 19...,https://cdn.anime-planet.com/manga/primary/joj...,4.7
3,A Sign of Affection,Romance Shoujo Slice of Life Disability Yuk...,https://cdn.anime-planet.com/manga/primary/a-s...,4.7
4,Moriarty the Patriot,Mystery Shounen Detectives England Europe ...,https://cdn.anime-planet.com/manga/primary/mor...,4.7

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 5000, stop_words='english')

In [12]:
manga.isnull().sum()

title     0
tags      0
cover     0
rating    0
dtype: int64

In [19]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [39]:
count=0
number = 0
for i in cv.get_feature_names_out():
    number+=1
    if (i == 'movie'):
        count +=1
        break
print(count, number)

1 2905

In [41]:
cv.get_feature_names_out()[2904]

'movie'

In [20]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [21]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [22]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\User\AppData\Local\Temp\ipykernel_6512\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [23]:
vectors.shape

(28000, 5000)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity = cosine_similarity(vectors)

Since size of similarity will be very big so taking only small data

In [43]:
similarity.shape

(11527, 11527)

In [71]:
anime[anime['Name'] == 'Naruto'].index[0]

678

In [78]:
(sorted(list(enumerate(similarity[0])),reverse=True, key = lambda x:x[1])[1:6])

[(12, 0.4567501391955698),
 (976, 0.3990119375605064),
 (8, 0.3834824944236852),
 (9572, 0.36742346141747667),
 (10375, 0.36273812505500586)]

In [28]:
def recommend(anime_name):
    anime_index = anime[anime['Name'] == anime_name].index[0]
    distances = similarity[anime_index] #array
    anime_list = sorted(list(enumerate(distances)),reverse=True, key = lambda x:x[1])[1:11] #gives anime index along with distance
    
    for i in anime_list:
        print(anime.iloc[i[0]]['Name'])

In [40]:
recommend('In Another World With My Smartphone')

Demon Lord, Retry!
Overlord II
Tsukimichi: Moonlit Fantasy
Mushoku Tensei: Jobless Reincarnation - Part II
Nabari no Ou
Overlord: The Dark Hero
Arifureta: From Commonplace to World's Strongest
Arifureta: From Commonplace to World's Strongest 2nd Season
By the Grace of the Gods
That Time I Got Reincarnated as a Slime

In [93]:
anime.iloc[9572]['Tags']

'elsi and haqua fli through the air, tri their best to captur a demon! kazuhiroyamada action fantasi demon base on a manga 2011 movi'

In [28]:
import pickle

In [30]:
pickle.dump(new_df.to_dict(), open('manga_dict.pkl', 'wb'))

In [29]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))