In [4]:
import numpy as np 
import pandas as pd

In [168]:
anime = pd.read_csv('Anime.csv')

In [169]:

anime.head()

,Rank,Name,Japanese_name,Type,Episodes,Studio,Release_season,Tags,Rating,Release_year,End_year,Description,Content_Warning,Related_Mange,Related_anime,Voice_actors,staff
0,1,Demon Slayer: Kimetsu no Yaiba - Entertainment...,Kimetsu no Yaiba: Yuukaku-hen,TV,NaN,ufotable,Fall,"Action, Adventure, Fantasy, Shounen, Demons, H...",4.60,2021.0,NaN,'Tanjiro and his friends accompany the Hashira...,Explicit Violence,Demon Slayer: Kimetsu no Yaiba,"Demon Slayer: Kimetsu no Yaiba, Demon Slayer: ...","Inosuke Hashibira : Yoshitsugu Matsuoka, Nezuk...","Koyoharu Gotouge : Original Creator, Haruo Sot..."
1,2,Fruits Basket the Final Season,Fruits Basket the Final,TV,13.0,TMS Entertainment,Spring,"Drama, Fantasy, Romance, Shoujo, Animal Transf...",4.60,2021.0,NaN,'The final arc of Fruits Basket.',"Emotional Abuse,, Mature Themes,, Physical Abu...","Fruits Basket, Fruits Basket Another","Fruits Basket 1st Season, Fruits Basket 2nd Se...","Akito Sohma : Maaya Sakamoto, Kyo Sohma : Yuum...","Natsuki Takaya : Original Creator, Yoshihide I..."
2,3,Mo Dao Zu Shi 3,The Founder of Diabolism 3,Web,12.0,B.C MAY PICTURES,NaN,"Fantasy, Ancient China, Chinese Animation, Cul...",4.58,2021.0,NaN,'The third season of Mo Dao Zu Shi.',NaN,Grandmaster of Demonic Cultivation: Mo Dao Zu ...,"Mo Dao Zu Shi 2, Mo Dao Zu Shi Q","Lan Wangji, Wei Wuxian, Jiang Cheng, Jin Guang...","Mo Xiang Tong Xiu : Original Creator, Xiong Ke..."
3,4,Fullmetal Alchemist: Brotherhood,Hagane no Renkinjutsushi: Full Metal Alchemist,TV,64.0,Bones,Spring,"Action, Adventure, Drama, Fantasy, Mystery, Sh...",4.58,2009.0,2010.0,"""The foundation of alchemy is based on the law...","Animal Abuse,, Mature Themes,, Violence,, Dome...","Fullmetal Alchemist, Fullmetal Alchemist (Ligh...","Fullmetal Alchemist: Brotherhood Specials, Ful...","Alphonse Elric : Rie Kugimiya, Edward Elric : ...","Hiromu Arakawa : Original Creator, Yasuhiro Ir..."
4,5,Attack on Titan 3rd Season: Part II,Shingeki no Kyojin Season 3: Part II,TV,10.0,WIT Studio,Spring,"Action, Fantasy, Horror, Shounen, Dark Fantasy...",4.57,2019.0,NaN,'The battle to retake Wall Maria begins now! W...,"Cannibalism,, Explicit Violence","Attack on Titan, Attack on Titan: End of the W...","Attack on Titan, Attack on Titan 2nd Season, A...","Armin Arlelt : Marina Inoue, Eren Jaeger : Yuu...","Hajime Isayama : Original Creator, Tetsurou Ar..."

In [7]:
anime.shape

(18495, 17)

In [19]:
anime.iloc[0]['Description']

"'Tanjiro and his friends accompany the Hashira Tengen Uzui to an entertainment district where Tengen’s female ninja agents were gathering information on a demon before they suddenly disappeared. In order to investigate, Tanjiro and the others disguise themselves as women to sneak in!'"

In [20]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18495 entries, 0 to 18494
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rank             18495 non-null  int64
 1   Name             18495 non-null  object
 2   Japanese_name    7938 non-null   object
 3   Type             18495 non-null  object
 4   Episodes         9501 non-null   float64
 5   Studio           12018 non-null  object
 6   Release_season   4116 non-null   object
 7   Tags             18095 non-null  object
 8   Rating           15364 non-null  float64
 9   Release_year     18112 non-null  float64
 10  End_year         2854 non-null   float64
 11  Description      18491 non-null  object
 12  Content_Warning  1840 non-null   object
 13  Related_Mange    7627 non-null   object
 14  Related_anime    10063 non-null  object
 15  Voice_actors     15309 non-null  object
 16  staff            13005 non-null  object
dtypes: float64(4), int64(1), object(12)
memory usage: 2.4+ MB

In [95]:
#rank
#Name
#Episodes
#Tags
#Rating
#Release_year
#Description
#staff

anime = anime[['Rank', 'Name', 'Episodes', 'Tags', 'Rating', 'Release_year', 'Description', 'staff']]

In [101]:
anime.iloc[500:505][:]

,Rank,Name,Episodes,Tags,Rating,Release_year,Description,staff
500,501,Stand by Me Doraemon,1.0,"Comedy, Drama, Sci Fi, Shounen, Cats, Family F...",4.12,2014.0,'No synopsis yet - check back soon!',"Fujiko F. Fujio : Original Creator, Takashi Ya..."
501,502,Sekai-ichi Hatsukoi: World's Greatest First Lo...,2.0,"BL, Comedy, Romance, Shounen-ai, Romantic Come...",4.12,2011.0,'Ritsu Onodera has been admiring a classmate f...,"Shungiku Nakamura : Original Creator, Chiaki K..."
502,503,Magical Girl Lyrical Nanoha: The Movie 2nd A's,1.0,"Fantasy, Magical Girl, Seinen, Contemporary Fa...",4.12,2012.0,'Six months have passed since the events of th...,"Keizou Kusakawa : Director, Misa Chuujou : Mus..."
503,504,"The Garden of Sinners Movie 3: Ever Cry, Never...",1.0,"Drama, Mystery, Overpowered Main Characters, S...",4.12,2008.0,"'On a solemn night in July 1998, teenager Fuji...","Kinoko Nasu : Original Creator, Takashi Takeuc..."
504,505,Gintama: Jump Festa 2015,1.0,"Comedy, Sci Fi, Shounen, Aliens, Gag, Parody, ...",4.12,2015.0,"""The Gintama crew gets together to present a p...",Hideaki Sorachi : Original Creator

In [34]:
anime.iloc[12]['staff']

'Koyoharu Gotouge : Original Creator, Haruo Sotozaki : Director, Ufotable : Series Composition, Gou Shiina : Music, Yuki Kajiura : Music & Song Arrangement & Song Composition & Song Lyrics, Akira Matsushima : Character Design, Masanori Miyake : Producer, Yuuma Takahashi : Producer'

In [96]:
anime.isnull().sum()

Rank               0
Name               0
Episodes        8994
Tags             400
Rating          3131
Release_year     383
Description        4
staff           5490
dtype: int64

In [68]:
anime.isnull().iloc[0]['Tags']

False

In [75]:
anime.iloc[0]['Name']

'Demon Slayer: Kimetsu no Yaiba - Entertainment District Arc'

In [160]:
anime.fillna({'Rating': 1}, inplace=True)

In [89]:
anime.dropna(inplace=True)

In [140]:
anime.shape

(15993, 8)

In [167]:
anime.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [162]:
null_data = anime[anime['staff'].isnull()]

In [163]:
null_data.head(7)

,Rank,Name,Episodes,Tags,Rating,Release_year,Description,staff
47,48,Demon Slayer: Kimetsu no Yaiba - Mugen Train,1.0,"Action, Drama, Fantasy, Shounen, Demons, Histo...",4.43,2021.0,'Tanjirou\xa0and the group have completed thei...,NaN
122,123,The Legend of Hei,1.0,"Action, Adventure, Fantasy, Animal Characteris...",4.32,2019.0,"'In bustling human world, various of goblins l...",NaN
162,163,Hikari: Be My Light,1.0,"BL, Drama, Shounen-ai, Illness, Psychological,...",4.28,2020.0,'No synopsis yet - check back soon!',NaN
208,209,Yuri!!! on Ice: Welcome to The Madness,1.0,"Sports, Ice Skating, Original Work",4.25,2017.0,'No synopsis yet - check back soon!',NaN
234,235,School Babysitters Special,1.0,"Comedy, Shoujo, Slice of Life, Childcare, Life...",4.24,2018.0,'No synopsis yet - check back soon!',NaN
261,262,Gintama: The Semi-Final,2.0,"Comedy, Sci Fi, Shounen, Aliens, Crude, Feudal...",4.23,2021.0,'A dTV exclusive online special.',NaN
351,352,Psychic Princess,16.0,"Comedy, Drama, Romance, Ancient China, Chinese...",4.18,2018.0,"""Qian Yunxi, the eldest daughter of the Grand ...",NaN

In [135]:
anime = anime.dropna(subset=['Rating', 'staff'], how ='all')

In [166]:
anime.isnull().sum()

AttributeError: 'NoneType' object has no attribute 'isnull'

In [157]:
anime = anime[~(anime['Rating'].isnull() & (anime['Rank']>1000))]

In [164]:
anime= anime.dropna(inplace=True)

2